data_path :
  - 'data/blink_grit_tongue_EPOCX_224293_2024.12.01T13.58.55+08.00.md.csv'
data_shuffle : False
batch_size : 4
seed : 8
num_epochs : 100
train_split : 0.6
val_split : 0.2
total_sec : 600
sample_intention : [1, 3,5,2]
class_names : ['Blink','Girt', 'Tongue', 'Rest']
sr : 128
duration : 4
segment_marks : [4,4,4,4,4,4]