data_path :
  - 'data/blink left and right still_EPOCX_224293_2024.08.27T17.26.23+08.00.md.csv'
exp_name : '10min_blink_left_right'
batch_size : 4
seed : 7
num_epochs : 100
train_split : 0.6
val_split : 0.2
total_sec : 600
sample_intention : [1, 3]
class_names : ['Left', 'Right']
sr : 128
duration : 2
segment_marks : [3,2,3,2]