data_path :
  - 'data/first experiment_EPOCX_233333_2024.08.13T14.30.43+08.00.md.csv'
exp_name : '10min_left_right'
batch_size : 4
seed : 7
num_epochs : 100
train_split : 0.6
val_split : 0.2
total_sec : 600
sample_intention : [1, 3]
class_names : ['Left', 'Right']
sr : 128
duration : 10